Changed package to callback abstract
Dhii/callback-abstract pull request #3
Opened 2018-01-15 13:48 UTC by XedinUnknown

Aims to incorporate solution for #2.

2018-01-15 13:53 UTC, mecha requested changes
Kindly remove `.idea/misc.xml` from version control and rename `.idea/callback-aware-trait.iml` to `.idea/callback-abstract.iml`.

Also, I've been noticing that `.idea/php.xml` does not use the `$PROJECT_DIR$` placeholder. Maybe we ought to stop committing that and adding it to `.gitignore`.

The only thing that PHPStorm needs to recognize that a folder is a project is the `.idea/*.iml` file.

2018-01-15 14:37 UTC, mecha commented
@XedinUnknown Actually, my projects' `.idea/php.xml` files are correctly using the `$PROJECT_DIR$` placeholder. Perhaps your paths are incorrect?

2018-01-15 15:03 UTC, XedinUnknown commented
@mecha, not sure exactly. Just removed the `misc.xml` for now.

2018-01-16 11:18 UTC, mecha requested changes
Over all, I love this. I'm only requesting a couple of small things relating to docs.

2018-01-16 11:18 UTC, mecha commented on src/InvokeCallbackCapableTrait.php
> +             * catch it, wrap, and trow a more appropriate exception.
Typo in _"trow"_

2018-01-16 11:18 UTC, mecha commented on src/InvokeCallbackCapableTrait.php
> +     * @return callable
Missing return description.

2018-01-16 13:21 UTC, mecha approved these changes

2018-01-16 13:27 UTC, merged